name: cardmarket_wizard
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.2.3 <4.0.0"
dependencies:
  async: ^2.11.0
  collection: ^1.18.0
  flutter:
    sdk: flutter
  html: ^0.15.4
  http: ^1.1.2
  logging: ^1.2.0
  micha_core: ^0.5.1
  puppeteer: ^3.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.9
flutter:
  uses-material-design: true
