name: cardmarket_wizard
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.4.3 <4.0.0"
dependencies:
  async: ^2.11.0
  collection: ^1.18.0
  flutter:
    sdk: flutter
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  fuzzywuzzy: ^1.1.6
  html: ^0.15.4
  http: ^1.2.2
  json_annotation: ^4.9.0
  logging: ^1.2.0
  meta: ^1.12.0
  micha_core: ^1.0.1
  puppeteer: ^3.12.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.2
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
flutter:
  uses-material-design: true
