name: cardmarket_wizard
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.6.2 <4.0.0"
dependencies:
  async: ^2.11.0
  collection: ^1.19.0
  flutter:
    sdk: flutter
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  fuzzywuzzy: ^1.2.0
  html: ^0.15.5
  http: ^1.3.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.15.0
  micha_core: ^1.1.0
  puppeteer: ^3.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.8
  build_runner: ^2.4.15
  json_serializable: ^6.9.0
flutter:
  uses-material-design: true
