name: cardmarket_wizard
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.32.8"
dependencies:
  async: ^2.13.0
  collection: ^1.19.1
  flutter:
    sdk: flutter
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
  fuzzywuzzy: ^1.2.0
  html: ^0.15.6
  http: ^1.5.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.16.0
  micha_core: ^2.0.0
  puppeteer: ^3.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.25.15
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
flutter:
  uses-material-design: true
